services:
  mongodb7:
    image: mongo:7-jammy
    container_name: mongodb7
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db:delegated
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=pass"

networks:
  default:
    external: true
    name: mongodb
