services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    hostname: home-assistant
    privileged: true
    restart: ${DOCKER_RESTART_POLICY:-no}
    network_mode: host
    env_file:
      - .env
    volumes:
      - $PWD/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home-assistant.rule=Host(`home-assistant.loc`)"
      - "traefik.http.routers.home-assistant.entrypoints=http,https"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
    networks:
      - default
      - traefik

networks:
  default:
    name: homeassistant
  traefik:
    external: true
