services:
  postgres17:
    image: postgres:17-alpine
    container_name: postgres17
    hostname: postgres17
    restart: ${DOCKER_RESTART_POLICY:-no}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:${PGDATA:-/var/lib/postgresql/data/pgdata}

networks:
  default:
    external: true
    name: postgres
