services:
  rabbitmq:
    image: bitnami/rabbitmq:3.13
    container_name: rabbitmq3
    hostname: rabbitmq3
    env_file:
      - .docker.env
    ports:
      - "5672:5672"
    volumes:
      - ./data:/bitnami:delegated

networks:
  default:
    external: true
    name: rabbitmq
