services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    network_mode: host
    restart: ${DOCKER_RESTART_POLICY:-no}
    env_file:
      - .env
    volumes:
      - $PWD/config:/config
      - $PWD/cache:/cache
      - ${JELLYFIN_MEDIA_PATH:-$PWD/media}:/media:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.loc`)"
      - "traefik.http.routers.jellyfin.entrypoints=http,https"
    networks:
      - default
      - traefik

networks:
  default:
    name: adguard
  traefik:
    external: true
