services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch8
    hostname: elasticsearch8
    environment:
      - ES_JAVA_OPTS=-Xms4096m -Xmx4096m
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data:delegated
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

networks:
  default:
    external: true
    name: elasticsearch
