version: "3.9"
services:
  mongodb42:
    image: mongo:4.2
    container_name: mongodb42
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db:delegated
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=pass"

networks:
  default:
    external: true
    name: mongodb
