services:
  mysql80:
    image: mysql:8.0-debian
    container_name: mysql80
    hostname: mysql80
    restart: ${DOCKER_RESTART_POLICY:-no}
    env_file:
      - .env
    ports:
      - "33060:3306"
    volumes:
      - ./data:/var/lib/mysql:delegated
      - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ./logs:/logs

networks:
  default:
    external: true
    name: mysql
