tls:
  certificates:
    - certFile: "/etc/traefik/certs/_wildcard.loc.pem"
      keyfile: "/etc/traefik/certs/_wildcard.loc-key.pem"
      stores:
        - default

  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/_wildcard.loc.pem"
        keyFile: "/etc/traefik/certs/_wildcard.loc-key.pem"

http:
  middlewares:
    https-redirect:
      redirectscheme:
        scheme: "https"
        permanent: true
